// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsClub.Models;

#nullable disable

namespace SportsClub.Migrations
{
    [DbContext(typeof(SportsClubContext))]
    [Migration("20230530183702_inti")]
    partial class inti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SportsClub.Models.PaymentGatway", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DeployKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentGatways");
                });

            modelBuilder.Entity("SportsClub.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SportsClub.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("ServiceTimeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTimeId");

                    b.HasIndex(new[] { "ServiceTypeId" }, "IX_ServicesServiceTypeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("SportsClub.Models.ServiceTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<TimeSpan>("FromTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ToTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ServiceTimes");
                });

            modelBuilder.Entity("SportsClub.Models.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("SportsClub.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "users_email_unique")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportsClub.Models.UserDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_UserDetailUserId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ISPayed")
                        .HasColumnType("bit");

                    b.Property<double>("TotaAmount")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserSubscriptionId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscriptionPaymentGatway", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PaymentGatwayId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserSubscriptionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserSubscriptionServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionServiceId");

                    b.HasIndex(new[] { "PaymentGatwayId" }, "IX_PaymentGatway");

                    b.HasIndex(new[] { "UserSubscriptionId" }, "IX_UserSubscriptionPaymentGatwayUserSubscriptionId");

                    b.ToTable("UserServicePaymentGatways");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscriptionService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("UserSubscriptionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_SUserSubscriptionServiceServiceId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserSubscriptionServiceUserID");

                    b.ToTable("UserSubscriptionServices");
                });

            modelBuilder.Entity("SportsClub.Models.Service", b =>
                {
                    b.HasOne("SportsClub.Models.ServiceTime", "ServiceTime")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTimeId")
                        .HasConstraintName("services_service_time_id_foreign");

                    b.HasOne("SportsClub.Models.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("services_service_type_id_foreign");

                    b.Navigation("ServiceTime");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("SportsClub.Models.UserDetail", b =>
                {
                    b.HasOne("SportsClub.Models.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("SportsClub.Models.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserSetails_user_id_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscription", b =>
                {
                    b.HasOne("SportsClub.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("UserSubscriptions_user_id_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscriptionPaymentGatway", b =>
                {
                    b.HasOne("SportsClub.Models.PaymentGatway", "PaymentGatway")
                        .WithMany("UserServicePaymentGatways")
                        .HasForeignKey("PaymentGatwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserServicePaymentGatwayPaymentGatway_id_foreign");

                    b.HasOne("SportsClub.Models.UserSubscription", "UserSubscription")
                        .WithMany("UserServicePaymentGatways")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserServicePaymentGatwayUserService_id_foreign");

                    b.HasOne("SportsClub.Models.UserSubscriptionService", null)
                        .WithMany("UserServicePaymentGatways")
                        .HasForeignKey("UserSubscriptionServiceId");

                    b.Navigation("PaymentGatway");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscriptionService", b =>
                {
                    b.HasOne("SportsClub.Models.Service", "Service")
                        .WithMany("UserServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserService_services_type_id_foreign");

                    b.HasOne("SportsClub.Models.User", "User")
                        .WithMany("UserSubscriptionServices")
                        .HasForeignKey("UserId")
                        .HasConstraintName("UserSubscriptionServices_user_id_foreign");

                    b.HasOne("SportsClub.Models.UserSubscription", "UserSubscription")
                        .WithMany("UserSubscriptionServices")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("SportsClub.Models.PaymentGatway", b =>
                {
                    b.Navigation("UserServicePaymentGatways");
                });

            modelBuilder.Entity("SportsClub.Models.Service", b =>
                {
                    b.Navigation("UserServices");
                });

            modelBuilder.Entity("SportsClub.Models.ServiceTime", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("SportsClub.Models.ServiceType", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("SportsClub.Models.User", b =>
                {
                    b.Navigation("UserDetail");

                    b.Navigation("UserSubscriptionServices");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscription", b =>
                {
                    b.Navigation("UserServicePaymentGatways");

                    b.Navigation("UserSubscriptionServices");
                });

            modelBuilder.Entity("SportsClub.Models.UserSubscriptionService", b =>
                {
                    b.Navigation("UserServicePaymentGatways");
                });
#pragma warning restore 612, 618
        }
    }
}
